### ISSUE TITLE
NoTranslator does not implements TranslatorBagInterface - conflict with Symfony 2.6

### ISSUE THREAD

**Issue by krzysztof-alboszta** [braincrafted/testing-bundle#11]
as Symfony 2.6 brings the logging for missing translation feature in Translation component the LoggerTranslator throws exception

    [InvalidArgumentException]
    The Translator "Braincrafted\Bundle\TestingBundle\Translator\NoTranslator" must implements TranslatorInterface and TranslatorBagInterface.

to avoid that there is option in framework configuration
````yaml
framework:
   translator:
       logging: false
````
which would be worth to mention in configuration instructions

**Comment by florianeckerstorfer** [comment]
I released a new v0.4 which implements `TranslatorBagInterface` and is therefore compatible with Symfony 2.6+. If you want to use TestingBundle with Symfony <2.6 please use a release from the `0.3` branch.

**Comment by krzysztof-alboszta** [comment]
OK thanks for the release

2015-02-06 12:12 GMT+01:00 Florian Eckerstorfer <notifications@github.com>:
